// https://tssl.yarb00.dev

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

namespace TsslInterpreter;

internal enum CriticalError
{
	Unknown = 1,
	InvalidArguments,
	FileReadError, EmptyFile,
	NotSupportedLanguageVersion,
	InvalidCode
}

internal static class Program
{
	public const string Website = "https://tssl.yarb00.dev";
	public const string Name = "TsslInterpreter";
	public static readonly string Title = Name + (Version is not null ? $" v{Version.ToString(3)}" : string.Empty);
	public static readonly Version? Version = Assembly.GetExecutingAssembly().GetName().Version;

	private const string issueReportUrl = $"{Website}/issue/report/client/?title=[ISSUE_TITLE]&body=[ISSUE_BODY]";

	private static readonly Dictionary<CriticalError, string> messageByErrorType = new()
	{
		[CriticalError.InvalidArguments] = "You should pass exactly 1 argument: the path to the code file.",
		[CriticalError.FileReadError] = "An error occurred while reading the code file. Does it exist? Is it accessible?",
		[CriticalError.EmptyFile] = "The code file is empty.",
		[CriticalError.NotSupportedLanguageVersion] = "The TSSL version specified in this script is not supported by this version of interpreter.",
		[CriticalError.InvalidCode] = "Your code contains an error."
	};

	public static void Main(string[] args)
	{
		Console.Title = Title;

		if (!Debugger.IsAttached) AppDomain.CurrentDomain.UnhandledException += static (_, e) => HandleUnhandledException((Exception)e.ExceptionObject);

		Console.CancelKeyPress += (_, _) => Exit(shouldKillProcess: false);

		if (args.Length != 1)
		{
			Console.WriteLine($"""
				Usage:
					Run TSSL code from a file:
						{Name} <file path>
					Print {Name} version:
						{Name} --version
						{Name} -v
					Check for {Name} updates (requires an internet connection):
						{Name} --check-updates
						{Name} -u
				""");

			Panic(CriticalError.InvalidArguments);
		}

		if (new string[] { "--version", "-v", "--check-updates", "-u" }.Contains(args[0]) && Version is null) Panic();
		else if (args[0] is "--version" or "-v" && Version is not null) Console.WriteLine(Version.ToString(3));
		else if (args[0] is "--check-updates" or "-u" && Version is not null) CheckUpdates();
		else RunCodeFromFile(args[0]);
	}

	private static void HandleUnhandledException(Exception e)
	{
		static string GetOSData() => RuntimeInformation.OSDescription;

		string
			issueTitle = $"Unhandled exception: `{e.GetType().Name}`",
			issueBody = $"""
					***Auto-generated by {Name}.***

					## Environment

					**{Name} version**: `{Version?.ToString(3) ?? "[Not available or not present.]"}`
					**OS**: `{GetOSData()}`

					## Exception info

					**Exception type**: `{e.GetType().FullName}`
					**Exception message**: `{e.Message}`
					**Inner exception type**: `{e.InnerException?.GetType().FullName ?? "[Not available or not present.]"}`
					**Inner exception message**: `{e.InnerException?.Message ?? "[Not available or not present.]"}`

					### Stack trace (inner exception)

					{e.InnerException?.StackTrace?.Replace("   ", "    ") ?? "`[Not available or not present.]`"}

					### Stack trace

					{e.StackTrace?.Replace("   ", "    ") ?? "`[Not available or not present.]`"}
					""",
			issueCreateLink = issueReportUrl
				.Replace("[ISSUE_TITLE]", issueTitle.Linkify())
				.Replace("[ISSUE_BODY]", issueBody.Linkify());

		Exit($"""
			An unhandled exception occurred!
			It's a serious error that should not normally happen.
			Please report it by visiting the URL below and reporting an issue (report should be already prefilled).
			Note that you would need a GitHub account to do so.

			Issue create link:
			{issueCreateLink}

			If you know what you're doing, here are advanced details:
			{e}
			""", shouldKillProcess: false);
	}

	private static void CheckUpdates()
	{
		Console.WriteLine(Title);
		Console.WriteLine(new string('=', Title.Length));
		Console.WriteLine("Fetching the latest version from the internet...");

		UpdateData updateData = Updater.GetUpdateData().GetAwaiter().GetResult();

		if (!Updater.IsUpdateAvailable(updateData))
		{
			Console.WriteLine("You're using the latest version.");
			return;
		}

		Console.WriteLine($"""
			A newer version is available!

			Installed version: {Version?.ToString(3) ?? "[An error occurred.]"}
			Latest version: {updateData.LatestVersion?.ToString(3) ?? "[An error occurred.]"}

			Download the update and read more about it here:
			{updateData.DetailsUrl?.ToString() ?? "[An error occurred.]"}
			""");
	}

	private static void RunCodeFromFile(string filePath)
	{
		string[] codeLines;

		try
		{
			codeLines = File.ReadAllLines(filePath);
		}
		catch
		{
			Panic(CriticalError.FileReadError);
			return;
		}

		if (codeLines.Length == 0) Panic(CriticalError.EmptyFile);

		new ScriptEnvironment(codeLines).ExecuteScript();
	}

	public static void Panic(CriticalError error = CriticalError.Unknown, string? message = null)
	{
		if (message is null && !messageByErrorType.TryGetValue(error, out message)) message = "An error occurred.";

		Exit(message, (int)error);
	}

	public static void Exit(string message = "", int exitCode = 0, bool shouldKillProcess = true)
	{
		Console.WriteLine();

		if (exitCode != 0) Console.WriteLine($"""
			{new string('=', Title.Length)}
			{Name} had to close. Reason:
			"{message}"
			""");

		if (shouldKillProcess) Environment.Exit(exitCode);
	}
}
