// https://yarb00.dev

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;

namespace TsslInterpreter;

internal enum CriticalError
{
	WrongArguments,
	FileReadError,
	EmptyFile,
	NotSupportedLanguageVersion,
	CodeError
}

internal static class Program
{
	private readonly static Dictionary<CriticalError, (string errorMessage, int exitCode)> errorDataByErrorType = new()
	{
		[CriticalError.WrongArguments] = ("You should pass exactly 1 argument: the path to the code file.", 2),
		[CriticalError.FileReadError] = ("An error occurred while reading the code file. (does it exist? is it accessible?)", 3),
		[CriticalError.EmptyFile] = ("The code file is empty.", 4),
		[CriticalError.NotSupportedLanguageVersion] = ("The TSSL version specified in this script is not supported by this version of interpreter.", 5),
		[CriticalError.CodeError] = ("Your code contains an error.", 6)
	};

	public readonly static Version? Version = Assembly.GetExecutingAssembly().GetName().Version;
	private readonly static string title = $"TsslInterpreter{(Version is not null ? $" v{Version.ToString(3)}" : string.Empty)}";

	public const string Name = "TsslInterpreter";

	public static void Main(string[] args)
	{
		Console.Title = title;

		if (!Debugger.IsAttached) AppDomain.CurrentDomain.UnhandledException += static (s, e) =>
		{
			string
				issueTitle = $"Unhandled exception: \"{((Exception)e.ExceptionObject).GetType().FullName}\"",
				issueBody = $"""
					***Auto-generated by TsslInterpreter.***

					## Environment
					**TsslInterpreter version**: `{Assembly.GetExecutingAssembly().GetName().Version?.ToString(3) ?? "[Not available or not present.]"}`
					**OS**: `{System.Runtime.InteropServices.RuntimeInformation.OSDescription}`

					## Exception info
					**Exception type**: `{((Exception)e.ExceptionObject).GetType().FullName}`
					**Exception message**: `{((Exception)e.ExceptionObject).Message}`
					**Inner exception type**: `{((Exception)e.ExceptionObject).InnerException?.GetType().FullName ?? "[Not available or not present.]"}`
					**Inner exception message**: `{((Exception)e.ExceptionObject).InnerException?.Message ?? "[Not available or not present.]"}`

					### Stack trace (inner exception)
					{((Exception)e.ExceptionObject).InnerException?.StackTrace?.Replace("   ", "    ") ?? "[Not available or not present.]"}
					### Stack trace
					{((Exception)e.ExceptionObject).StackTrace?.Replace("   ", "    ") ?? "[Not available or not present.]"}
					""",
				issueCreateLink = $"https://github.com/yarb00/TsslInterpreter/issues/new?title={Linkify(issueTitle)}&body={Linkify(issueBody)}";

			Console.WriteLine($"""
				{new string('=', title.Length)}
				An unhandled exception occurred!
				It's a serious error that should not normally happen.
				Please report it by pasting the URL below, logging in or creating a GitHub account, and filling an issue.

				Report URL: {issueCreateLink}

				If you know what you're doing, here are advanced details:

				Exception message: {((Exception)e.ExceptionObject).Message}
				Inner exception message: {((Exception)e.ExceptionObject).InnerException?.Message ?? "[Not available or not present.]"}
				===== Stack trace (inner exception): =====
				{((Exception)e.ExceptionObject).InnerException?.StackTrace ?? "[Not available or not present.]"}
				===== Stack trace: =====
				{((Exception)e.ExceptionObject).StackTrace ?? "[Not available or not present.]"}
				""");
		};

		AppDomain.CurrentDomain.ProcessExit += (s, e) => Exit(shouldKillProcess: false);
		Console.CancelKeyPress += (s, e) => Exit(shouldKillProcess: false);

		if (args.Length != 1) Panic(CriticalError.WrongArguments);

		if (args[0] == "--version" && Version is not null) Console.WriteLine(Version.ToString(3));
		else if (args[0] == "--version" && Version is null) Panic();
		else RunCodeFromFile(args[0]);
	}

	private static string Linkify(string text) => text
		.Replace(' ', '+')
		.Replace("#", "%23")
		.Replace("\"", "%22")
		.Replace("/", "%2F")
		.Replace("&", "%26")
		.ReplaceLineEndings("%0A");

	private static void RunCodeFromFile(string filePath)
	{
		string[] codeLines;

		try
		{
			codeLines = File.ReadAllLines(filePath);
		}
		catch
		{
			Panic(CriticalError.FileReadError);
			return;
		}

		if (codeLines.Length == 0) Panic(CriticalError.EmptyFile);

		ScriptEnvironment environment = new();
		foreach (string codeLine in codeLines) environment.RunInstruction(codeLine);
	}

	public static void Panic(CriticalError? errorType = null)
	{
		if (errorType is null || !errorDataByErrorType.TryGetValue((CriticalError)errorType, out (string message, int exitCode) error))
			Exit("An unknown error occurred.", 1);
		else Exit(error.message, error.exitCode);
	}

	public static void Exit(string message = "Bye.", int exitCode = 0, bool shouldKillProcess = true)
	{
		Console.WriteLine(new string('=', title.Length));
		Console.WriteLine(message);
		if (shouldKillProcess) Environment.Exit(exitCode);
	}
}
