<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <VersionPrefix>0.6.0</VersionPrefix>

    <!-- File properties -->
    <AssemblyTitle>TSSL::Interpreter</AssemblyTitle>
    <Product>TSSL::Interpreter</Product>
    <Copyright>Copyright (c) yarb00 2025-2026</Copyright>
  </PropertyGroup>

</Project>
