# https://tssl.yarb00.dev

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Publish (Release)
    strategy:
      matrix:
        os:
          - runner_name: ubuntu-24.04
            dotnet_rid: linux-x64
          - runner_name: windows-2025
            dotnet_rid: win-x64
    runs-on: ${{ matrix.os.runner_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.100
      - name: Build
        run: dotnet publish -r ${{ matrix.os.dotnet_rid }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: TsslInterpreter (${{ matrix.os.runner_name }}) (Release) (${{ matrix.os.dotnet_rid }})
          path: src/bin/Release/net10.0/${{ matrix.os.dotnet_rid }}/publish
          if-no-files-found: error
